### ISSUE TITLE
Last commit breaks SilverStripe 4 dev/build

### ISSUE THREAD

**Issue by digitweaks** [silvershop/silverstripe-sqlquerylist#13]
Hi everyone, I was installing Silvershop on a fresh installation of SilverStripe 4.13 and after long debugging I realized the last commit of this module doesn't pass the dev/build. I used another version I installed few weeks ago and it went through.

**Comment by wilr** [comment]
@Digitweaks What's the error message?

**Comment by digitweaks** [comment]
@wilr I wish I could tell, I just had a blank page with no error message. Nothing special either in the console.

**Comment by EnricoLLC** [comment]
( ! ) Fatal error: Declaration of SilverShop\SQLQueryList\SQLQueryList::limit(?int $limit, int $offset = 0): SilverStripe\ORM\Limitable must be compatible with SilverStripe\ORM\Limitable::limit($limit, $offset = 0) in /mnt/noodlesoup/sstestenrico/vendor/silvershop/silverstripe-sqlquerylist/src/SQLQueryList.php on line 204

Line 204 of SQLQueryList.php has

```
    public function limit(?int $limit, int $offset = 0): Limitable
```

But Silverstripe's Limitable.php has

```
    public function limit($limit, $offset = 0);
```

**Comment by wilr** [comment]
For Silverstripe 4 keep on an [2.0.0](https://github.com/silvershop/silverstripe-sqlquerylist/releases/tag/2.0.0) release.
