### ISSUE TITLE
V 2.1.0 not compatible with Silverstripe CMS 4.13

### ISSUE THREAD

**Issue by wernerkrauss** [silvershop/silverstripe-sqlquerylist#14]
It seems like SS4.13 with PHP7.4 has a problem when Silvershop installs SQLQueryList V 2.1.0:

```
Fatal error: Declaration of SilverShop\SQLQueryList\SQLQueryList::limit(?int $limit, int $offset = 0): SilverStripe\ORM\Limitable must be compatible with SilverStripe\ORM\Limitable::limit($limit, $offset = 0) in /Users/tn/www/kazuriscandinavia/vendor/silvershop/silverstripe-sqlquerylist/src/SQLQueryList.php on line 204
```

A workaround for now is to install V2.0.0 manually

**Comment by wilr** [comment]
@wernerkrauss Sorry about that, might have been trigger happy.

To confirm https://github.com/silvershop/silverstripe-sqlquerylist/commit/3d828e57da6a8c3dcb6cd36192598df5e9367285 is the last commit that works for you?

**Comment by wernerkrauss** [comment]
Yes, as [V2.0.0](https://github.com/silvershop/silverstripe-sqlquerylist/commits/2.0.0) is commit https://github.com/silvershop/silverstripe-sqlquerylist/commit/3d828e57da6a8c3dcb6cd36192598df5e9367285 , it works for me on at least two projects

**Comment by wernerkrauss** [comment]
Closing this issue, as V2.1.0 got deleted
